#!/bin/bash
DEVICE=$(ip link | awk '{if(NR==3) print $2}' | cut -d ':' -f 1)

if [ "$(iw dev $DEVICE link)" == "Not connected." ]
then
	echo "<span color='red'>Not Connected</span>"
else

	SSID=$(iw dev $DEVICE link | awk '{if(NR==2) print $2}')

	DOWN1=$(awk -v dev=$DEVICE '{if($0~dev) print $2}' /proc/net/dev)
	UP1=$(awk -v dev=$DEVICE '{if($0~dev) print $10}' /proc/net/dev)
	sleep 1
	DOWN2=$(awk -v dev=$DEVICE '{if($0~dev) print $2}' /proc/net/dev)
	UP2=$(awk -v dev=$DEVICE '{if($0~dev) print $10}' /proc/net/dev)

	DOWN1=$((($DOWN2-$DOWN1)/1024))
	UP1=$((($UP2-$UP1)/1024))

	echo 🠳 $DOWN1'Kb' 🠱 $UP1'Kb'
fi
