(defconst my/IS-MAC     (eq system-type 'darwin))
(defconst my/IS-LINUX   (eq system-type 'gnu/linux))
(defconst my/IS-WINDOWS (memq system-type '(cygwin windows-nt ms-dos)))
(defconst my/IS-BSD     (eq system-type 'berkeley-unix))
(defconst my/HAS-JAVA t)
(defconst my/HAS-DOTNET nil)
