#!/bin/sh
export XIM=ibus
export GTK_IM_MODULE=ibus
export GTK3_IM_MODULE=ibus
export QT_IM_MODULE=ibus
export QT4_IM_MODULE=ibus
export XMODIFIERS="@im=ibus"
export XIM_PROGRAM=ibus

# remap the caps lock key to be another ctrl key
setxkbmap \
  -model pc105 \
  -layout "us" \
  -variant altgr-intl \
  -option compose:rctrl \
  -option ctrl:nocaps
  -option "grp:alt_shift_toggle" 

xset s on +dpms 
xrdb $HOME/.Xresources 
unclutter -root -onescreen &
xbindkeys &
autocutsel &                                                                         
numlockx on &
xidle -timeout 300 &
#compton --config ~/.compton/compton.conf &
#urxvtd -q -o -f & 
#sleep 3 && clipit &
#sleep 3 && openoffice-4.1.5 -quickstart &
#sleep 3 && networkmgr &
#sleep 3 && sbxkb &
#xsetroot -solid "#5A80A7"
exec fvwm2 

