#!/bin/sh

#export XIM=ibus
#export GTK_IM_MODULE=ibus
#export QT_IM_MODULE=xim
#export XMODIFIERS=@im=ibus
#export XIM_PROGRAM=ibus
#export XIM_PROGRAM="ibus-daemon"
#export XIM_ARGS="--daemonize --xim"

export XIM=fcitx
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=xim
export XMODIFIERS=@im=fcitx
export XIM_PROGRAM="fcitx"
export XIM_ARGS="-d -r"


xset s on +dpms 
xrdb $HOME/.Xresources 
#unclutter -root -onescreen &
#xbindkeys &
#autocutsel &                                
#numlockx on &
xidle -timeout 300 &
#compton --config ~/.compton/compton.conf &
#urxvtd -q -o -f & 
#sleep 3 && clipit &
#sleep 3 && openoffice-4.1.5 -quickstart &
#sleep 3 && networkmgr &
#sleep 3 && sbxkb &
#xsetroot -solid "#5A80A7"
#exec fvwm2 
exec i3

