# use UTF-8 everywhere
export QT_IM_MODULE=fcitx
export GTK_IM_MODULE=fcitx
export GTK3_IM_MODULE=fcitx
export XIM=fcitx
export XMODIFIERS=@im=fcitx
export LANG=en_US.UTF-8

# specify location of kshrc
export ENV=$HOME/.kshrc
export PATH HOME TERM

export QT_QPA_PLATFORMTHEME=qt5ct
export XDG_DATA_DIRS=/usr/local/share

# load Xresources file
xrdb -merge $HOME/.Xresources &

# disable system beep
xset b off &

# set your background color
xsetroot -solid gray40 &
exec dbus-launch --exit-with-session i3
