#
# ~/.bash_profile
#
export TERM=xterm-256color
[[ -f ~/.bashrc ]] && . ~/.bashrc

# erlang
test -r /home/david/.local/erl/activate && . /home/david/.local/erl/activate > /dev/null 2> /dev/null || true
# opam configuration
test -r /home/david/.opam/opam-init/init.sh && . /home/david/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
